name: Build RunAI Image

on:
  push:
    paths:
      - 'environment.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  PACK_VOLUME_KEY: "kirschnj-renku2runai-cache"
  BP_SBO_ENABLED: "false"
  PACK_VERSION: "0.38.2"
  IMAGE_BASE: ghcr.io/${{ toLower(github.repository) }}

jobs:
  build-runai-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: (Optional) Log in to GitLab registry to pull a private run-image
      #   uses: docker/login-action@v3
      #   with:
      #     registry: gitlab-registry.datascience.ch
      #     username: ${{ secrets.GITLAB_REGISTRY_USER }}
      #     password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}

      - name: Install pack
        run: |
          curl -sSL "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" | sudo tar -C /usr/local/bin -xz pack
          pack version

      - name: Build image with pack
        run: |
          set -euo pipefail
          pack build "$IMAGE_BASE/renku2runai:latest" \
            --builder ghcr.io/swissdatasciencecenter/renku-frontend-buildpacks/selector:0.1.0 \
            --run-image gitlab-registry.datascience.ch/kirschnj/renku2runai/runai-renku-base:latest \
            --pull-policy if-not-present \
            --buildpack renku/conda-nodefaults \
            --buildpack paketo-buildpacks/ca-certificates \
            --buildpack paketo-buildpacks/miniconda \
            --buildpack paketo-buildpacks/conda-env-update \
            --buildpack paketo-buildpacks/python-start \
            --buildpack renku/python-dependency-manager

      - name: Push images
        run: |
          set -euo pipefail
          docker push "$IMAGE_BASE/renku2runai:latest"